### ISSUE TITLE
Cross-platform compatibility

### ISSUE THREAD

**Issue by codeflight1** [c4ooo/YARK-MFD#1]
Hi,
This is a great project but I use linux and was wondering if you would mind me converting it to cross-platform using cmake so more people could use it.
Thanks for all your hard work!

**Comment by GeraKuznetsov** [comment]
Hmm, switching to a different build system would be the easy part. The code just isn't cross platform right now. Although most of the libs I use are cross platorm (freetype, SDL, GLM, GLEW), I wouldnt know how to set them up on linux. I also use winsock, which is windows only. If I have a couple days free, I'll see if I can install a copy of linux and try to make it cross-platform.

**Comment by codeflight1** [comment]
Well, I was experimenting a bit and got all but the client class compiling on linux with cmake, do you want me to push it to my fork so you could take a look? I will also try and find a cross-platform alternative to winsock and let you know if I find anything.

**Comment by GeraKuznetsov** [comment]
Sure! I think all the windows socket stuff and file IO can just be put in a wrapper file that uses #if-s to call either the windows or linux specific files.

**Comment by codeflight1** [comment]
Ok, I just pushed a huge commit to my fork and its now working on linux! I don't want to make a PR until you test it to make sure it works on windows too.

**Comment by GeraKuznetsov** [comment]
Ok cool, i'll test it a bit later. I see you also renamed and changed a bunch of stuff. Most of this is fine, except for the change at https://github.com/VA7NFH/YARK-MFD/commit/fd78ab927b24a104c3aeea985ebb346645c8d4cf#diff-61f31b7766b869c3bde27e20c3b62d39L137 NAN is used to signify that the 3 Euler angles don't have ANY value, as opposed to having a value of zero. IIRC though, the plugin doesn't check this anymore, so I guess this change is fine too.

**Comment by codeflight1** [comment]
Yeah, unfortunately it seems like gcc doesn't define NAN. We could just set it to something really big but I don't know if that would be better than 0.

**Comment by codeflight1** [comment]
Ok, it turns out it was just a missing header and I just pushed a fix.

**Comment by GeraKuznetsov** [comment]
I am not familiar with cmake. How does it know if it needs to link with the linux or windows versions of the libraries?

**Comment by codeflight1** [comment]
It has a built in function for finding library directories by name, although I think it is still set up to manually link on windows. If you don't want to use cmake, the visual studio build should still work.

**Comment by GeraKuznetsov** [comment]
Ok, that makes sense I guess.
One thing though: you changed the SDL.h header include to "#include <SDL2/SDL.h>", which is weird becouse in the release of SDL I have, the path of that header is "SDL2\include\SDL.h". So there is no way I can make the MSVS .sln file work if that is how the SDL.h is referenced in the source code. 
Anyways, feel free to make the PR, i'll fix it up.

**Comment by codeflight1** [comment]
Yeah, I think that's a platform specific thing.

**Comment by GeraKuznetsov** [comment]
I think your setup is wrong then. SDL wiki says you should refer to the header as <SDL.h>.
Amyways, thanks for the hardwork! Should I just assume the CMake works on linux? (Have you gotten the application to run?)

**Comment by codeflight1** [comment]
It turns out that in the CMakeLists.txt it has to be ${SDL2_INCLUDE_DIRS} instead of ${SDL2_INCLUDE_DIR} to make <SDL.h> work. And yes, I have gotten it to run.

**Comment by GeraKuznetsov** [comment]
I moved the CMake file outside of the source code folder (alongside the sln), and changed __WIN32 to _WIN32. I also switched to using the glm max/min for consistency. (Also undefed min/max since some windows headers define them and causes a conflict).

**Comment by codeflight1** [comment]
Okay, unfortunately moving CMakeLists.txt means that even though you changed the path it still can't find the source, you have to add it manually to each file name. And even if you do that, it can't find the textures (or the font but that's a different problem) so I would suggest moving it back.

**Comment by codeflight1** [comment]
Great! I think this can be closed now.
